### ISSUE TITLE
Adding support for python 3.7

### ISSUE THREAD

**Issue by ZebinYang** [vnmabus/dcor#49]
It seems that the latest version of dcor does not support py37, and the latest version for py37 is 0.5.3.

**Comment by vnmabus** [comment]
Yes, this is intentional. Software packages in the Scientific Python ecosystem usually try to follow [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html). This recommends dropping Python 3.7 support after 2021-12-26. You will see that other libraries, such as NumPy, do no support Python 3.7 in newer versions either (and will soon drop support for Python 3.8).

Dropping support for old Python versions in a scheduled way allow us to use newer functionalities and reduces the maintenance effort, specially for libraries with few developers such as this one.

That said, is there a particular reason for needing the latest changes in Python 3.7?
